### ISSUE TITLE
48kHz training

### ISSUE THREAD

**Issue by JBloodless** [Audio-WestlakeU/RVAE-EM#1]
Hi, thanks for such contribution!

Is it possible to train RVAE on 48 kHz data? If yes, what modifications of hyperparameters should I make?

**Comment by PengyvWANG** [comment]
Hi Ivan, I didn't try our method on 48kHz data. This repo is only for 16kHz data. 
Theoretically, for 48kHz audio a longer CTF filter, a longer STFT window, and a larger STFT hop size should be used.

**Comment by JBloodless** [comment]
> Hi Ivan, I didn't try our method on 48kHz data. This repo is only for 16kHz data.
> Theoretically, for 48kHz audio a longer CTF filter, a longer STFT window, and a larger STFT hop size should be used.

Should I make some modifications in the architecture? For example, convolution kernels size or smth else?

**Comment by PengyvWANG** [comment]
Sorry, I have to say that I haven't tried it yet. Therefore, I can't answer your question now. 
I recommend you to try it. I will also inform you and update the results if I do the experiments in the future.
