### ISSUE TITLE
使用pre-trained模型进行推理

### ISSUE THREAD

**Issue by shenbuguanni** [Audio-WestlakeU/RVAE-EM#4]
你好，我在你提供的网页下载了一个预训练好的模型：RVAEEMS_ckpt_0000100000
然后执行：
python enhance.py -c ./config.json  -p ./output/ --ckpt ./checkpoint/
已经修改了spch_dir,但是报错：RuntimeError: Trying to resize storage that is not resizable
请问是什么原因呢？显存是24G的

**Comment by PengyvWANG** [comment]
您好，请将您执行的指令以及您修改的config内容发一下，我看看问题出在哪

**Comment by shenbuguanni** [comment]
1.git clone https://github.com/Audio-WestlakeU/RVAE-EM.git
2.下载pre-trained模型：https://drive.google.com/drive/folders/1rI4h9hmJg7Gwv-pAVLUkRIzFOcxT-ZyJ
模型名字为：RVAEEMS_ckpt_0000100000，创建checkpoint文件夹，并存放该模型文件
3.创建test_wav文件夹，里面存放了待测混响语音xxx.wav
4.修改config/config_S.json中的“data_setting_test”中的“spch_dir”为3中的test_wav的绝对路径
5.执行：python enhance.py --config /home/xxx/RVAE-EM-main/config/config_S.json -p output_wav --ckpt ./checkpoint/RVAEEMS_ckpt_0000100000
然后结果报错：
RuntimeError: Trying to resize storage that is not resizable

**Comment by PengyvWANG** [comment]
试一下将config中batch_size的最后一维度改为1，并设置可见GPU为单个GPU，再进行test

**Comment by shenbuguanni** [comment]
非常感谢，已经可以跑了，效果上相比于传统NN去混响还是比较惊艳的，我有一些疑问想请教一下：
1.模型参数是7M,请问算力如何，比如多少Macs?
2.请问有没有应用在降噪领域，或者说这个模型是否合适用在降噪？
3.这个模型是因果的吗？我看有EM算法，是一帧进一帧出吗？还是只能非因果的？

**Comment by PengyvWANG** [comment]
您好，汇报的方法Macs约为37G/s；由于没有建模非平稳噪声，无法直接用于降噪；是非因果的算法，使用整段语音估计观测模型参数。
